name: {{packageName}}
description: "Flutter app"

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.8.0
  
dependencies:
  auto_route: ^10.1.2
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.0
  injectable: ^2.5.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.2.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1

dev_dependencies:
  analyzer: ^7.7.1
  arb_utils: ^0.1.0+1
  auto_route_generator: ^10.2.4
  auto_translator: ^2.3.5
  build_runner: ^2.7.1
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.1
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
