name: {{packageName}}
description: "Flutter app"

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"
  
dependencies:
  auto_route: ^10.2.3
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  google_fonts: ^6.3.2
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.1
  injectable: ^2.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  uuid: ^4.5.2

dev_dependencies:
  analyzer: ^8.0.0
  arb_utils: ^0.1.0+1
  auto_route_generator: ^10.2.6
  auto_translator: ^2.3.5
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
